import { createGroq } from "@ai-sdk/groq";
import { createMistral } from "@ai-sdk/mistral";
import { APICallError, generateText, Output, RetryError } from "ai";
import type { ZodType } from "zod";

// Reads the key from GROQ_API_KEY (the SDK default), spelled out so a missing key is easy to spot.
const groq = createGroq({ apiKey: process.env.GROQ_API_KEY });

// Reads the key from MISTRAL_API_KEY (the SDK default) or the MISTRAL_AI name used in this project's .env.
const mistral = createMistral({ apiKey: process.env.MISTRAL_API_KEY ?? process.env.MISTRAL_AI });

// Each model gets its own time limit, so one that hangs can't use up the whole request; 3 x 35s fits maxDuration.
const MODEL_TIMEOUT_MS = 35_000;
// Pause after a rate-limit response before trying the next model; the limit is account-wide, so switching alone doesn't help.
const RATE_LIMIT_PAUSE_MS = 2_000;
// Upper bound on the reply size; stops a small model from rambling (slow, and burns the free-tier quota).
const MAX_OUTPUT_TOKENS = 7_000;

// Models tried in order: the biggest first for better diagrams; a busy, rate-limited or unavailable one falls back to the next.
const MODELS = [
  { name: "openai/gpt-oss-20b", model: groq("openai/gpt-oss-20b") },
  { name: "ministral-14b-latest", model: mistral("ministral-14b-latest") },
  { name: "ministral-8b-latest", model: mistral("ministral-8b-latest") },
] as const;

// Unwraps the SDK's RetryError to the underlying API error, if any.
const getApiError = (error: unknown) => {
  const cause = RetryError.isInstance(error) ? error.lastError : error;
  return APICallError.isInstance(cause) ? cause : null;
};

// Whether an error means the model is overloaded or rate limited (worth trying later).
export const isBusyError = (error: unknown) => {
  const status = getApiError(error)?.statusCode;
  return status === 429 || status === 503;
};

// Whether this model's own time limit ran out (AbortSignal.timeout surfaces as a TimeoutError).
export const isTimeoutError = (error: unknown) => {
  const cause = RetryError.isInstance(error) ? error.lastError : error;
  return cause instanceof Error && cause.name === "TimeoutError";
};

// Whether another model is worth trying: busy, timed out, or not available on the account's plan (403/404).
const canTryNextModel = (error: unknown) => {
  const status = getApiError(error)?.statusCode;
  return isBusyError(error) || isTimeoutError(error) || status === 400 || status === 403 || status === 404;
};


// Short reason for logs: HTTP status and provider message, or the error name.
const describeError = (error: unknown) => {
  const apiError = getApiError(error);
  if (apiError) return `HTTP ${apiError.statusCode}: ${apiError.message}`;
  return error instanceof Error ? `${error.name}: ${error.message}` : String(error);
};


// Asks the models, in order, for an object that matches `schema`. A busy, slow or unavailable model falls through
// to the next one; any other error is thrown so the route can turn it into a response.
export const generateObjectWithFallback = async <SCHEMA extends ZodType>({
  schema,
  system,
  prompt,
}: {
  schema: SCHEMA;
  system: string;
  prompt: string;
}) => {
  let lastError: unknown;

  for (const { name, model } of MODELS) {
    try {
      const { output } = await generateText({
        model,
        output: Output.object({ schema }),
        system,
        prompt,
        temperature: 0.3,
        maxRetries: 1,
        maxOutputTokens: MAX_OUTPUT_TOKENS,
        abortSignal: AbortSignal.timeout(MODEL_TIMEOUT_MS),
        // Groq's strict json_schema mode rejects schemas with optional fields; plain JSON mode works, and our zod schema still validates the reply.
        providerOptions: { groq: { structuredOutputs: false } },
      });
      console.log(`Diagram generated by ${name}`);
      return output;
    } catch (error) {
      lastError = error;
      if (!canTryNextModel(error)) throw error;
      console.warn(`Model ${name} skipped (${describeError(error)}), trying the next one`);
      if (getApiError(error)?.statusCode === 429) {
        await new Promise((resolve) => setTimeout(resolve, RATE_LIMIT_PAUSE_MS));
      }
    }
  }

  throw lastError;
};